version: '2'
services:
  db:
    image: mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pagekit
      - MYSQL_DATABASE=pagekit
    volumes:
      - ~/docker/pagekit/mysql:/var/lib/mysql
  pagekit:
    image: pagekit/pagekit
    ports:
      - "8000:80"
    links:
      - db:db
    volumes:
      - ~/docker/pagekit/storage:/pagekit/storage
      - ~/docker/pagekit/app/cache:/pagekit/app/cache
